// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Character struct {
	ID            pgtype.UUID        `json:"id"`
	Version       int32              `json:"version"`
	Name          string             `json:"name"`
	Traits        []byte             `json:"traits"`
	VoiceSamples  []string           `json:"voice_samples"`
	Relationships []byte             `json:"relationships"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CharacterState struct {
	StoryID     pgtype.UUID        `json:"story_id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	AsOfNode    pgtype.UUID        `json:"as_of_node"`
	State       []byte             `json:"state"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Edge struct {
	StoryID  pgtype.UUID `json:"story_id"`
	FromNode pgtype.UUID `json:"from_node"`
	ToNode   pgtype.UUID `json:"to_node"`
	EdgeType string      `json:"edge_type"`
}

type Generation struct {
	ID             pgtype.UUID        `json:"id"`
	NodeID         pgtype.UUID        `json:"node_id"`
	ContextHash    string             `json:"context_hash"`
	PromptSnapshot string             `json:"prompt_snapshot"`
	Output         string             `json:"output"`
	Model          string             `json:"model"`
	Accepted       bool               `json:"accepted"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LatestCharacter struct {
	ID            pgtype.UUID        `json:"id"`
	Version       int32              `json:"version"`
	Name          string             `json:"name"`
	Traits        []byte             `json:"traits"`
	VoiceSamples  []string           `json:"voice_samples"`
	Relationships []byte             `json:"relationships"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LatestLocation struct {
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Props       []byte             `json:"props"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Location struct {
	ID          pgtype.UUID        `json:"id"`
	Version     int32              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Props       []byte             `json:"props"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Lore struct {
	ID        pgtype.UUID        `json:"id"`
	Tags      []string           `json:"tags"`
	Content   string             `json:"content"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID            pgtype.UUID        `json:"id"`
	StoryID       pgtype.UUID        `json:"story_id"`
	BeatIntent    string             `json:"beat_intent"`
	CharacterRefs []pgtype.UUID      `json:"character_refs"`
	LocationRef   pgtype.UUID        `json:"location_ref"`
	Pov           string             `json:"pov"`
	Tone          string             `json:"tone"`
	TargetWords   int32              `json:"target_words"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Story struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	CanonPins []byte             `json:"canon_pins"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
