// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const acceptGeneration = `-- name: AcceptGeneration :exec
UPDATE generations SET accepted = true WHERE id = $1
`

func (q *Queries) AcceptGeneration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptGeneration, id)
	return err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (name, traits, voice_samples, relationships)
VALUES ($1, $2, $3, $4)
RETURNING id, version, name, traits, voice_samples, relationships, created_at
`

type CreateCharacterParams struct {
	Name          string   `json:"name"`
	Traits        []byte   `json:"traits"`
	VoiceSamples  []string `json:"voice_samples"`
	Relationships []byte   `json:"relationships"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.Name,
		arg.Traits,
		arg.VoiceSamples,
		arg.Relationships,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
	)
	return i, err
}

const createEdge = `-- name: CreateEdge :exec
INSERT INTO edges (story_id, from_node, to_node, edge_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type CreateEdgeParams struct {
	StoryID  pgtype.UUID `json:"story_id"`
	FromNode pgtype.UUID `json:"from_node"`
	ToNode   pgtype.UUID `json:"to_node"`
	EdgeType string      `json:"edge_type"`
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.Exec(ctx, createEdge,
		arg.StoryID,
		arg.FromNode,
		arg.ToNode,
		arg.EdgeType,
	)
	return err
}

const createGeneration = `-- name: CreateGeneration :one
INSERT INTO generations (node_id, context_hash, prompt_snapshot, output, model)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, node_id, context_hash, prompt_snapshot, output, model, accepted, created_at
`

type CreateGenerationParams struct {
	NodeID         pgtype.UUID `json:"node_id"`
	ContextHash    string      `json:"context_hash"`
	PromptSnapshot string      `json:"prompt_snapshot"`
	Output         string      `json:"output"`
	Model          string      `json:"model"`
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, createGeneration,
		arg.NodeID,
		arg.ContextHash,
		arg.PromptSnapshot,
		arg.Output,
		arg.Model,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ContextHash,
		&i.PromptSnapshot,
		&i.Output,
		&i.Model,
		&i.Accepted,
		&i.CreatedAt,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, description, props)
VALUES ($1, $2, $3)
RETURNING id, version, name, description, props, created_at
`

type CreateLocationParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Props       []byte `json:"props"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Description, arg.Props)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const createLore = `-- name: CreateLore :one
INSERT INTO lore (tags, content, embedding)
VALUES ($1, $2, $3)
RETURNING id, tags, content, embedding, created_at
`

type CreateLoreParams struct {
	Tags      []string        `json:"tags"`
	Content   string          `json:"content"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateLore(ctx context.Context, arg CreateLoreParams) (Lore, error) {
	row := q.db.QueryRow(ctx, createLore, arg.Tags, arg.Content, arg.Embedding)
	var i Lore
	err := row.Scan(
		&i.ID,
		&i.Tags,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (story_id, beat_intent, character_refs, location_ref, pov, tone, target_words)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, story_id, beat_intent, character_refs, location_ref, pov, tone, target_words, status, created_at, updated_at
`

type CreateNodeParams struct {
	StoryID       pgtype.UUID   `json:"story_id"`
	BeatIntent    string        `json:"beat_intent"`
	CharacterRefs []pgtype.UUID `json:"character_refs"`
	LocationRef   pgtype.UUID   `json:"location_ref"`
	Pov           string        `json:"pov"`
	Tone          string        `json:"tone"`
	TargetWords   int32         `json:"target_words"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.StoryID,
		arg.BeatIntent,
		arg.CharacterRefs,
		arg.LocationRef,
		arg.Pov,
		arg.Tone,
		arg.TargetWords,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.BeatIntent,
		&i.CharacterRefs,
		&i.LocationRef,
		&i.Pov,
		&i.Tone,
		&i.TargetWords,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (title) VALUES ($1) RETURNING id, title, canon_pins, created_at
`

func (q *Queries) CreateStory(ctx context.Context, title string) (Story, error) {
	row := q.db.QueryRow(ctx, createStory, title)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CanonPins,
		&i.CreatedAt,
	)
	return i, err
}

const getAcceptedGenerationForNode = `-- name: GetAcceptedGenerationForNode :one
SELECT id, node_id, context_hash, prompt_snapshot, output, model, accepted, created_at FROM generations WHERE node_id = $1 AND accepted = true LIMIT 1
`

func (q *Queries) GetAcceptedGenerationForNode(ctx context.Context, nodeID pgtype.UUID) (Generation, error) {
	row := q.db.QueryRow(ctx, getAcceptedGenerationForNode, nodeID)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ContextHash,
		&i.PromptSnapshot,
		&i.Output,
		&i.Model,
		&i.Accepted,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterAtVersion = `-- name: GetCharacterAtVersion :one
SELECT id, version, name, traits, voice_samples, relationships, created_at FROM characters WHERE id = $1 AND version = $2
`

type GetCharacterAtVersionParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetCharacterAtVersion(ctx context.Context, arg GetCharacterAtVersionParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterAtVersion, arg.ID, arg.Version)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterLatest = `-- name: GetCharacterLatest :one
SELECT id, version, name, traits, voice_samples, relationships, created_at FROM latest_characters WHERE id = $1
`

func (q *Queries) GetCharacterLatest(ctx context.Context, id pgtype.UUID) (LatestCharacter, error) {
	row := q.db.QueryRow(ctx, getCharacterLatest, id)
	var i LatestCharacter
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterState = `-- name: GetCharacterState :one
SELECT story_id, character_id, as_of_node, state, updated_at FROM character_state
WHERE story_id = $1 AND character_id = $2 AND as_of_node = $3
`

type GetCharacterStateParams struct {
	StoryID     pgtype.UUID `json:"story_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	AsOfNode    pgtype.UUID `json:"as_of_node"`
}

func (q *Queries) GetCharacterState(ctx context.Context, arg GetCharacterStateParams) (CharacterState, error) {
	row := q.db.QueryRow(ctx, getCharacterState, arg.StoryID, arg.CharacterID, arg.AsOfNode)
	var i CharacterState
	err := row.Scan(
		&i.StoryID,
		&i.CharacterID,
		&i.AsOfNode,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncomingEdges = `-- name: GetIncomingEdges :many
SELECT story_id, from_node, to_node, edge_type FROM edges WHERE to_node = $1
`

func (q *Queries) GetIncomingEdges(ctx context.Context, toNode pgtype.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, getIncomingEdges, toNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.StoryID,
			&i.FromNode,
			&i.ToNode,
			&i.EdgeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationAtVersion = `-- name: GetLocationAtVersion :one
SELECT id, version, name, description, props, created_at FROM locations WHERE id = $1 AND version = $2
`

type GetLocationAtVersionParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetLocationAtVersion(ctx context.Context, arg GetLocationAtVersionParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationAtVersion, arg.ID, arg.Version)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationLatest = `-- name: GetLocationLatest :one
SELECT id, version, name, description, props, created_at FROM latest_locations WHERE id = $1
`

func (q *Queries) GetLocationLatest(ctx context.Context, id pgtype.UUID) (LatestLocation, error) {
	row := q.db.QueryRow(ctx, getLocationLatest, id)
	var i LatestLocation
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, story_id, beat_intent, character_refs, location_ref, pov, tone, target_words, status, created_at, updated_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.BeatIntent,
		&i.CharacterRefs,
		&i.LocationRef,
		&i.Pov,
		&i.Tone,
		&i.TargetWords,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutgoingEdges = `-- name: GetOutgoingEdges :many
SELECT story_id, from_node, to_node, edge_type FROM edges WHERE from_node = $1
`

func (q *Queries) GetOutgoingEdges(ctx context.Context, fromNode pgtype.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, getOutgoingEdges, fromNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.StoryID,
			&i.FromNode,
			&i.ToNode,
			&i.EdgeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatesAtBranch = `-- name: GetStatesAtBranch :many
SELECT DISTINCT ON (cs.character_id) cs.story_id, cs.character_id, cs.as_of_node, cs.state, cs.updated_at
FROM character_state cs
WHERE cs.story_id = $1 AND cs.as_of_node = $2
ORDER BY cs.character_id, cs.as_of_node DESC
`

type GetStatesAtBranchParams struct {
	StoryID  pgtype.UUID `json:"story_id"`
	AsOfNode pgtype.UUID `json:"as_of_node"`
}

func (q *Queries) GetStatesAtBranch(ctx context.Context, arg GetStatesAtBranchParams) ([]CharacterState, error) {
	rows, err := q.db.Query(ctx, getStatesAtBranch, arg.StoryID, arg.AsOfNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterState{}
	for rows.Next() {
		var i CharacterState
		if err := rows.Scan(
			&i.StoryID,
			&i.CharacterID,
			&i.AsOfNode,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatesForNode = `-- name: GetStatesForNode :many
SELECT story_id, character_id, as_of_node, state, updated_at FROM character_state
WHERE story_id = $1 AND as_of_node = $2
`

type GetStatesForNodeParams struct {
	StoryID  pgtype.UUID `json:"story_id"`
	AsOfNode pgtype.UUID `json:"as_of_node"`
}

func (q *Queries) GetStatesForNode(ctx context.Context, arg GetStatesForNodeParams) ([]CharacterState, error) {
	rows, err := q.db.Query(ctx, getStatesForNode, arg.StoryID, arg.AsOfNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterState{}
	for rows.Next() {
		var i CharacterState
		if err := rows.Scan(
			&i.StoryID,
			&i.CharacterID,
			&i.AsOfNode,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStory = `-- name: GetStory :one
SELECT id, title, canon_pins, created_at FROM stories WHERE id = $1
`

func (q *Queries) GetStory(ctx context.Context, id pgtype.UUID) (Story, error) {
	row := q.db.QueryRow(ctx, getStory, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CanonPins,
		&i.CreatedAt,
	)
	return i, err
}

const isGenerationStale = `-- name: IsGenerationStale :one
SELECT COUNT(*) > 0 FROM generations
WHERE node_id = $1 AND context_hash != $2
`

type IsGenerationStaleParams struct {
	NodeID      pgtype.UUID `json:"node_id"`
	ContextHash string      `json:"context_hash"`
}

func (q *Queries) IsGenerationStale(ctx context.Context, arg IsGenerationStaleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGenerationStale, arg.NodeID, arg.ContextHash)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, version, name, traits, voice_samples, relationships, created_at FROM latest_characters ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]LatestCharacter, error) {
	rows, err := q.db.Query(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestCharacter{}
	for rows.Next() {
		var i LatestCharacter
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Name,
			&i.Traits,
			&i.VoiceSamples,
			&i.Relationships,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdges = `-- name: ListEdges :many
SELECT story_id, from_node, to_node, edge_type FROM edges WHERE story_id = $1
`

func (q *Queries) ListEdges(ctx context.Context, storyID pgtype.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdges, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.StoryID,
			&i.FromNode,
			&i.ToNode,
			&i.EdgeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationsForNode = `-- name: ListGenerationsForNode :many
SELECT id, node_id, context_hash, prompt_snapshot, output, model, accepted, created_at FROM generations WHERE node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGenerationsForNode(ctx context.Context, nodeID pgtype.UUID) ([]Generation, error) {
	rows, err := q.db.Query(ctx, listGenerationsForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Generation{}
	for rows.Next() {
		var i Generation
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ContextHash,
			&i.PromptSnapshot,
			&i.Output,
			&i.Model,
			&i.Accepted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, version, name, description, props, created_at FROM latest_locations ORDER BY name
`

func (q *Queries) ListLocations(ctx context.Context) ([]LatestLocation, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestLocation{}
	for rows.Next() {
		var i LatestLocation
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Props,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLore = `-- name: ListLore :many
SELECT id, tags, content, embedding, created_at FROM lore ORDER BY created_at DESC
`

func (q *Queries) ListLore(ctx context.Context) ([]Lore, error) {
	rows, err := q.db.Query(ctx, listLore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lore{}
	for rows.Next() {
		var i Lore
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, story_id, beat_intent, character_refs, location_ref, pov, tone, target_words, status, created_at, updated_at FROM nodes WHERE story_id = $1 ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context, storyID pgtype.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.BeatIntent,
			&i.CharacterRefs,
			&i.LocationRef,
			&i.Pov,
			&i.Tone,
			&i.TargetWords,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStories = `-- name: ListStories :many
SELECT id, title, canon_pins, created_at FROM stories ORDER BY created_at DESC
`

func (q *Queries) ListStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.Query(ctx, listStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CanonPins,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectOtherGenerations = `-- name: RejectOtherGenerations :exec
UPDATE generations SET accepted = false
WHERE node_id = $1 AND id != $2
`

type RejectOtherGenerationsParams struct {
	NodeID pgtype.UUID `json:"node_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RejectOtherGenerations(ctx context.Context, arg RejectOtherGenerationsParams) error {
	_, err := q.db.Exec(ctx, rejectOtherGenerations, arg.NodeID, arg.ID)
	return err
}

const searchLoreByTags = `-- name: SearchLoreByTags :many
SELECT id, tags, content, embedding, created_at FROM lore WHERE tags && $1::text[] ORDER BY created_at DESC
`

func (q *Queries) SearchLoreByTags(ctx context.Context, dollar_1 []string) ([]Lore, error) {
	rows, err := q.db.Query(ctx, searchLoreByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lore{}
	for rows.Next() {
		var i Lore
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLoreSimilar = `-- name: SearchLoreSimilar :many
SELECT id, tags, content, embedding, created_at FROM lore
ORDER BY embedding <=> $1::vector
LIMIT $2
`

type SearchLoreSimilarParams struct {
	Column1 pgvector.Vector `json:"column_1"`
	Limit   int32           `json:"limit"`
}

func (q *Queries) SearchLoreSimilar(ctx context.Context, arg SearchLoreSimilarParams) ([]Lore, error) {
	rows, err := q.db.Query(ctx, searchLoreSimilar, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lore{}
	for rows.Next() {
		var i Lore
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes SET status = $2, updated_at = now() WHERE id = $1
`

type SetNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.Exec(ctx, setNodeStatus, arg.ID, arg.Status)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :one
INSERT INTO characters (id, version, name, traits, voice_samples, relationships)
SELECT c.id, MAX(c.version) + 1, c.name, CAST($2 AS jsonb), $3, CAST($4 AS jsonb)
FROM characters c WHERE c.id = $1
GROUP BY c.id, c.name
RETURNING id, version, name, traits, voice_samples, relationships, created_at
`

type UpdateCharacterParams struct {
	ID           pgtype.UUID `json:"id"`
	Column2      []byte      `json:"column_2"`
	VoiceSamples []string    `json:"voice_samples"`
	Column4      []byte      `json:"column_4"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.ID,
		arg.Column2,
		arg.VoiceSamples,
		arg.Column4,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
INSERT INTO locations (id, version, name, description, props)
SELECT $1, MAX(version) + 1, name, $2, CAST($3 AS jsonb)
FROM locations WHERE id = $1
GROUP BY id, name
RETURNING id, version, name, description, props, created_at
`

type UpdateLocationParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	Column3     []byte      `json:"column_3"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation, arg.ID, arg.Description, arg.Column3)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET
    beat_intent = $2, character_refs = $3, location_ref = $4,
    pov = $5, tone = $6, target_words = $7, updated_at = now()
WHERE id = $1
RETURNING id, story_id, beat_intent, character_refs, location_ref, pov, tone, target_words, status, created_at, updated_at
`

type UpdateNodeParams struct {
	ID            pgtype.UUID   `json:"id"`
	BeatIntent    string        `json:"beat_intent"`
	CharacterRefs []pgtype.UUID `json:"character_refs"`
	LocationRef   pgtype.UUID   `json:"location_ref"`
	Pov           string        `json:"pov"`
	Tone          string        `json:"tone"`
	TargetWords   int32         `json:"target_words"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.BeatIntent,
		arg.CharacterRefs,
		arg.LocationRef,
		arg.Pov,
		arg.Tone,
		arg.TargetWords,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.BeatIntent,
		&i.CharacterRefs,
		&i.LocationRef,
		&i.Pov,
		&i.Tone,
		&i.TargetWords,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoryCanonPins = `-- name: UpdateStoryCanonPins :exec
UPDATE stories SET canon_pins = $2 WHERE id = $1
`

type UpdateStoryCanonPinsParams struct {
	ID        pgtype.UUID `json:"id"`
	CanonPins []byte      `json:"canon_pins"`
}

func (q *Queries) UpdateStoryCanonPins(ctx context.Context, arg UpdateStoryCanonPinsParams) error {
	_, err := q.db.Exec(ctx, updateStoryCanonPins, arg.ID, arg.CanonPins)
	return err
}

const upsertCharacterState = `-- name: UpsertCharacterState :exec
INSERT INTO character_state (story_id, character_id, as_of_node, state)
VALUES ($1, $2, $3, $4)
ON CONFLICT (story_id, character_id, as_of_node)
DO UPDATE SET state = $4, updated_at = now()
`

type UpsertCharacterStateParams struct {
	StoryID     pgtype.UUID `json:"story_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	AsOfNode    pgtype.UUID `json:"as_of_node"`
	State       []byte      `json:"state"`
}

func (q *Queries) UpsertCharacterState(ctx context.Context, arg UpsertCharacterStateParams) error {
	_, err := q.db.Exec(ctx, upsertCharacterState,
		arg.StoryID,
		arg.CharacterID,
		arg.AsOfNode,
		arg.State,
	)
	return err
}
