// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const acceptGeneration = `-- name: AcceptGeneration :exec
UPDATE generations SET accepted = true WHERE id = $1
`

func (q *Queries) AcceptGeneration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptGeneration, id)
	return err
}

const assignTrait = `-- name: AssignTrait :exec
INSERT INTO character_trait_assignments (character_id, trait_id, intensity, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (character_id, trait_id) DO UPDATE SET intensity = $3, note = $4
`

type AssignTraitParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	TraitID     pgtype.UUID `json:"trait_id"`
	Intensity   int32       `json:"intensity"`
	Note        string      `json:"note"`
}

func (q *Queries) AssignTrait(ctx context.Context, arg AssignTraitParams) error {
	_, err := q.db.Exec(ctx, assignTrait,
		arg.CharacterID,
		arg.TraitID,
		arg.Intensity,
		arg.Note,
	)
	return err
}

const countSummariesByLevel = `-- name: CountSummariesByLevel :one
SELECT COUNT(*) FROM story_summaries
WHERE story_id = $1 AND level = $2
`

type CountSummariesByLevelParams struct {
	StoryID pgtype.UUID `json:"story_id"`
	Level   string      `json:"level"`
}

func (q *Queries) CountSummariesByLevel(ctx context.Context, arg CountSummariesByLevelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSummariesByLevel, arg.StoryID, arg.Level)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActor = `-- name: CreateActor :one
INSERT INTO actors (name, gender, ethnicity, race, skin_tone, eye_color, hair_color, hair_style, build, height_cm, weight_kg, age, nationality, traits)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, name, gender, ethnicity, race, skin_tone, eye_color, hair_color, hair_style, build, height_cm, weight_kg, age, nationality, traits, created_at
`

type CreateActorParams struct {
	Name        string `json:"name"`
	Gender      string `json:"gender"`
	Ethnicity   string `json:"ethnicity"`
	Race        string `json:"race"`
	SkinTone    string `json:"skin_tone"`
	EyeColor    string `json:"eye_color"`
	HairColor   string `json:"hair_color"`
	HairStyle   string `json:"hair_style"`
	Build       string `json:"build"`
	HeightCm    int32  `json:"height_cm"`
	WeightKg    int32  `json:"weight_kg"`
	Age         int32  `json:"age"`
	Nationality string `json:"nationality"`
	Traits      []byte `json:"traits"`
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error) {
	row := q.db.QueryRow(ctx, createActor,
		arg.Name,
		arg.Gender,
		arg.Ethnicity,
		arg.Race,
		arg.SkinTone,
		arg.EyeColor,
		arg.HairColor,
		arg.HairStyle,
		arg.Build,
		arg.HeightCm,
		arg.WeightKg,
		arg.Age,
		arg.Nationality,
		arg.Traits,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Ethnicity,
		&i.Race,
		&i.SkinTone,
		&i.EyeColor,
		&i.HairColor,
		&i.HairStyle,
		&i.Build,
		&i.HeightCm,
		&i.WeightKg,
		&i.Age,
		&i.Nationality,
		&i.Traits,
		&i.CreatedAt,
	)
	return i, err
}

const createCasting = `-- name: CreateCasting :one
INSERT INTO casting (story_id, actor_id, character_id, role_type)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, actor_id, character_id, role_type, created_at
`

type CreateCastingParams struct {
	StoryID     pgtype.UUID `json:"story_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	RoleType    string      `json:"role_type"`
}

func (q *Queries) CreateCasting(ctx context.Context, arg CreateCastingParams) (Casting, error) {
	row := q.db.QueryRow(ctx, createCasting,
		arg.StoryID,
		arg.ActorID,
		arg.CharacterID,
		arg.RoleType,
	)
	var i Casting
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ActorID,
		&i.CharacterID,
		&i.RoleType,
		&i.CreatedAt,
	)
	return i, err
}

const createChapter = `-- name: CreateChapter :one

INSERT INTO chapters (story_id, title, goal, order_index)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, title, goal, order_index, summary, status, created_at, updated_at
`

type CreateChapterParams struct {
	StoryID    pgtype.UUID `json:"story_id"`
	Title      string      `json:"title"`
	Goal       string      `json:"goal"`
	OrderIndex int32       `json:"order_index"`
}

// ── Chapters ─────────────────────────────────────────────────────────
func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.StoryID,
		arg.Title,
		arg.Goal,
		arg.OrderIndex,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Title,
		&i.Goal,
		&i.OrderIndex,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (name, persona, backstory, moral_alignment, personality, flaws, goals, traits, voice_samples, relationships, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, version, name, traits, voice_samples, relationships, created_at, persona, backstory, moral_alignment, personality, flaws, goals, parent_id
`

type CreateCharacterParams struct {
	Name           string      `json:"name"`
	Persona        string      `json:"persona"`
	Backstory      string      `json:"backstory"`
	MoralAlignment string      `json:"moral_alignment"`
	Personality    []byte      `json:"personality"`
	Flaws          []byte      `json:"flaws"`
	Goals          []byte      `json:"goals"`
	Traits         []byte      `json:"traits"`
	VoiceSamples   []string    `json:"voice_samples"`
	Relationships  []byte      `json:"relationships"`
	ParentID       pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.Name,
		arg.Persona,
		arg.Backstory,
		arg.MoralAlignment,
		arg.Personality,
		arg.Flaws,
		arg.Goals,
		arg.Traits,
		arg.VoiceSamples,
		arg.Relationships,
		arg.ParentID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
		&i.Persona,
		&i.Backstory,
		&i.MoralAlignment,
		&i.Personality,
		&i.Flaws,
		&i.Goals,
		&i.ParentID,
	)
	return i, err
}

const createCharacterTrait = `-- name: CreateCharacterTrait :one
INSERT INTO character_traits (name, category, description)
VALUES ($1, $2, $3)
RETURNING id, name, category, description, created_at
`

type CreateCharacterTraitParams struct {
	Name        string `json:"name"`
	Category    string `json:"category"`
	Description string `json:"description"`
}

func (q *Queries) CreateCharacterTrait(ctx context.Context, arg CreateCharacterTraitParams) (CharacterTrait, error) {
	row := q.db.QueryRow(ctx, createCharacterTrait, arg.Name, arg.Category, arg.Description)
	var i CharacterTrait
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createGeneration = `-- name: CreateGeneration :one

INSERT INTO generations (scene_id, context_hash, prompt_snapshot, output, model)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, scene_id, context_hash, prompt_snapshot, output, model, accepted, created_at, validation_result
`

type CreateGenerationParams struct {
	SceneID        pgtype.UUID `json:"scene_id"`
	ContextHash    string      `json:"context_hash"`
	PromptSnapshot string      `json:"prompt_snapshot"`
	Output         string      `json:"output"`
	Model          string      `json:"model"`
}

// ── Generations ──────────────────────────────────────────────────────
func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, createGeneration,
		arg.SceneID,
		arg.ContextHash,
		arg.PromptSnapshot,
		arg.Output,
		arg.Model,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.ContextHash,
		&i.PromptSnapshot,
		&i.Output,
		&i.Model,
		&i.Accepted,
		&i.CreatedAt,
		&i.ValidationResult,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, description, props)
VALUES ($1, $2, $3)
RETURNING id, version, name, description, props, created_at
`

type CreateLocationParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Props       []byte `json:"props"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Description, arg.Props)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const createLore = `-- name: CreateLore :one
INSERT INTO lore (tags, content, embedding)
VALUES ($1, $2, $3)
RETURNING id, tags, content, embedding, created_at
`

type CreateLoreParams struct {
	Tags      []string        `json:"tags"`
	Content   string          `json:"content"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) CreateLore(ctx context.Context, arg CreateLoreParams) (Lore, error) {
	row := q.db.QueryRow(ctx, createLore, arg.Tags, arg.Content, arg.Embedding)
	var i Lore
	err := row.Scan(
		&i.ID,
		&i.Tags,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const createScene = `-- name: CreateScene :one

INSERT INTO scenes (chapter_id, story_id, beat_intent, character_refs, location_ref, pov, tone, target_words)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chapter_id, story_id, title, beat_intent, character_refs, location_ref, pov, tone, target_words, scene_structure, parent_scene_id, timeline_position, flow_type, max_turns, status, created_at, updated_at
`

type CreateSceneParams struct {
	ChapterID     pgtype.UUID   `json:"chapter_id"`
	StoryID       pgtype.UUID   `json:"story_id"`
	BeatIntent    string        `json:"beat_intent"`
	CharacterRefs []pgtype.UUID `json:"character_refs"`
	LocationRef   pgtype.UUID   `json:"location_ref"`
	Pov           string        `json:"pov"`
	Tone          string        `json:"tone"`
	TargetWords   int32         `json:"target_words"`
}

// ── Scenes ───────────────────────────────────────────────────────────
func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.ChapterID,
		arg.StoryID,
		arg.BeatIntent,
		arg.CharacterRefs,
		arg.LocationRef,
		arg.Pov,
		arg.Tone,
		arg.TargetWords,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.StoryID,
		&i.Title,
		&i.BeatIntent,
		&i.CharacterRefs,
		&i.LocationRef,
		&i.Pov,
		&i.Tone,
		&i.TargetWords,
		&i.SceneStructure,
		&i.ParentSceneID,
		&i.TimelinePosition,
		&i.FlowType,
		&i.MaxTurns,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSceneEdge = `-- name: CreateSceneEdge :exec

INSERT INTO scene_edges (story_id, from_scene, to_scene, edge_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type CreateSceneEdgeParams struct {
	StoryID   pgtype.UUID `json:"story_id"`
	FromScene pgtype.UUID `json:"from_scene"`
	ToScene   pgtype.UUID `json:"to_scene"`
	EdgeType  string      `json:"edge_type"`
}

// ── Scene Edges ──────────────────────────────────────────────────────
func (q *Queries) CreateSceneEdge(ctx context.Context, arg CreateSceneEdgeParams) error {
	_, err := q.db.Exec(ctx, createSceneEdge,
		arg.StoryID,
		arg.FromScene,
		arg.ToScene,
		arg.EdgeType,
	)
	return err
}

const createSceneTurn = `-- name: CreateSceneTurn :one

INSERT INTO scene_turns (scene_id, turn_number, actor_ids, prompt, output, model, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, scene_id, turn_number, actor_ids, prompt, output, model, status, created_at
`

type CreateSceneTurnParams struct {
	SceneID    pgtype.UUID   `json:"scene_id"`
	TurnNumber int32         `json:"turn_number"`
	ActorIds   []pgtype.UUID `json:"actor_ids"`
	Prompt     string        `json:"prompt"`
	Output     string        `json:"output"`
	Model      string        `json:"model"`
	Status     string        `json:"status"`
}

// ── Scene Turns ──────────────────────────────────────────────────────
func (q *Queries) CreateSceneTurn(ctx context.Context, arg CreateSceneTurnParams) (SceneTurn, error) {
	row := q.db.QueryRow(ctx, createSceneTurn,
		arg.SceneID,
		arg.TurnNumber,
		arg.ActorIds,
		arg.Prompt,
		arg.Output,
		arg.Model,
		arg.Status,
	)
	var i SceneTurn
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.TurnNumber,
		&i.ActorIds,
		&i.Prompt,
		&i.Output,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one

INSERT INTO stories (title, genre, theme, main_prompt, general_prompt)
VALUES ($1, '', '', '', '')
RETURNING id, title, canon_pins, created_at, genre, theme, main_prompt, general_prompt
`

// ── Stories ──────────────────────────────────────────────────────────
func (q *Queries) CreateStory(ctx context.Context, title string) (Story, error) {
	row := q.db.QueryRow(ctx, createStory, title)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CanonPins,
		&i.CreatedAt,
		&i.Genre,
		&i.Theme,
		&i.MainPrompt,
		&i.GeneralPrompt,
	)
	return i, err
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM chapters WHERE id = $1
`

func (q *Queries) DeleteChapter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapter, id)
	return err
}

const deleteScene = `-- name: DeleteScene :exec
DELETE FROM scenes WHERE id = $1
`

func (q *Queries) DeleteScene(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScene, id)
	return err
}

const deleteStorySummary = `-- name: DeleteStorySummary :exec
DELETE FROM story_summaries WHERE id = $1
`

func (q *Queries) DeleteStorySummary(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorySummary, id)
	return err
}

const getAcceptedGenerationForScene = `-- name: GetAcceptedGenerationForScene :one
SELECT id, scene_id, context_hash, prompt_snapshot, output, model, accepted, created_at, validation_result FROM generations WHERE scene_id = $1 AND accepted = true LIMIT 1
`

func (q *Queries) GetAcceptedGenerationForScene(ctx context.Context, sceneID pgtype.UUID) (Generation, error) {
	row := q.db.QueryRow(ctx, getAcceptedGenerationForScene, sceneID)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.ContextHash,
		&i.PromptSnapshot,
		&i.Output,
		&i.Model,
		&i.Accepted,
		&i.CreatedAt,
		&i.ValidationResult,
	)
	return i, err
}

const getActor = `-- name: GetActor :one
SELECT id, name, gender, ethnicity, race, skin_tone, eye_color, hair_color, hair_style, build, height_cm, weight_kg, age, nationality, traits, created_at FROM actors WHERE id = $1
`

func (q *Queries) GetActor(ctx context.Context, id pgtype.UUID) (Actor, error) {
	row := q.db.QueryRow(ctx, getActor, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Ethnicity,
		&i.Race,
		&i.SkinTone,
		&i.EyeColor,
		&i.HairColor,
		&i.HairStyle,
		&i.Build,
		&i.HeightCm,
		&i.WeightKg,
		&i.Age,
		&i.Nationality,
		&i.Traits,
		&i.CreatedAt,
	)
	return i, err
}

const getChapter = `-- name: GetChapter :one
SELECT id, story_id, title, goal, order_index, summary, status, created_at, updated_at FROM chapters WHERE id = $1
`

func (q *Queries) GetChapter(ctx context.Context, id pgtype.UUID) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Title,
		&i.Goal,
		&i.OrderIndex,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterAtVersion = `-- name: GetCharacterAtVersion :one
SELECT id, version, name, traits, voice_samples, relationships, created_at, persona, backstory, moral_alignment, personality, flaws, goals, parent_id FROM characters WHERE id = $1 AND version = $2
`

type GetCharacterAtVersionParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetCharacterAtVersion(ctx context.Context, arg GetCharacterAtVersionParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterAtVersion, arg.ID, arg.Version)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
		&i.Persona,
		&i.Backstory,
		&i.MoralAlignment,
		&i.Personality,
		&i.Flaws,
		&i.Goals,
		&i.ParentID,
	)
	return i, err
}

const getCharacterLatest = `-- name: GetCharacterLatest :one
SELECT id, version, name, persona, backstory, moral_alignment, personality, flaws, goals, traits, voice_samples, relationships, parent_id, created_at FROM latest_characters WHERE id = $1
`

func (q *Queries) GetCharacterLatest(ctx context.Context, id pgtype.UUID) (LatestCharacter, error) {
	row := q.db.QueryRow(ctx, getCharacterLatest, id)
	var i LatestCharacter
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Persona,
		&i.Backstory,
		&i.MoralAlignment,
		&i.Personality,
		&i.Flaws,
		&i.Goals,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterState = `-- name: GetCharacterState :one
SELECT story_id, character_id, as_of_scene, state, updated_at FROM character_state
WHERE story_id = $1 AND character_id = $2 AND as_of_scene = $3
`

type GetCharacterStateParams struct {
	StoryID     pgtype.UUID `json:"story_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	AsOfScene   pgtype.UUID `json:"as_of_scene"`
}

func (q *Queries) GetCharacterState(ctx context.Context, arg GetCharacterStateParams) (CharacterState, error) {
	row := q.db.QueryRow(ctx, getCharacterState, arg.StoryID, arg.CharacterID, arg.AsOfScene)
	var i CharacterState
	err := row.Scan(
		&i.StoryID,
		&i.CharacterID,
		&i.AsOfScene,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterTrait = `-- name: GetCharacterTrait :one
SELECT id, name, category, description, created_at FROM character_traits WHERE id = $1
`

func (q *Queries) GetCharacterTrait(ctx context.Context, id pgtype.UUID) (CharacterTrait, error) {
	row := q.db.QueryRow(ctx, getCharacterTrait, id)
	var i CharacterTrait
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getIncomingSceneEdges = `-- name: GetIncomingSceneEdges :many
SELECT story_id, from_scene, to_scene, edge_type, condition FROM scene_edges WHERE to_scene = $1
`

func (q *Queries) GetIncomingSceneEdges(ctx context.Context, toScene pgtype.UUID) ([]SceneEdge, error) {
	rows, err := q.db.Query(ctx, getIncomingSceneEdges, toScene)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneEdge{}
	for rows.Next() {
		var i SceneEdge
		if err := rows.Scan(
			&i.StoryID,
			&i.FromScene,
			&i.ToScene,
			&i.EdgeType,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationAtVersion = `-- name: GetLocationAtVersion :one
SELECT id, version, name, description, props, created_at FROM locations WHERE id = $1 AND version = $2
`

type GetLocationAtVersionParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetLocationAtVersion(ctx context.Context, arg GetLocationAtVersionParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationAtVersion, arg.ID, arg.Version)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationLatest = `-- name: GetLocationLatest :one
SELECT id, version, name, description, props, created_at FROM latest_locations WHERE id = $1
`

func (q *Queries) GetLocationLatest(ctx context.Context, id pgtype.UUID) (LatestLocation, error) {
	row := q.db.QueryRow(ctx, getLocationLatest, id)
	var i LatestLocation
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const getOutgoingSceneEdges = `-- name: GetOutgoingSceneEdges :many
SELECT story_id, from_scene, to_scene, edge_type, condition FROM scene_edges WHERE from_scene = $1
`

func (q *Queries) GetOutgoingSceneEdges(ctx context.Context, fromScene pgtype.UUID) ([]SceneEdge, error) {
	rows, err := q.db.Query(ctx, getOutgoingSceneEdges, fromScene)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneEdge{}
	for rows.Next() {
		var i SceneEdge
		if err := rows.Scan(
			&i.StoryID,
			&i.FromScene,
			&i.ToScene,
			&i.EdgeType,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScene = `-- name: GetScene :one
SELECT id, chapter_id, story_id, title, beat_intent, character_refs, location_ref, pov, tone, target_words, scene_structure, parent_scene_id, timeline_position, flow_type, max_turns, status, created_at, updated_at FROM scenes WHERE id = $1
`

func (q *Queries) GetScene(ctx context.Context, id pgtype.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, getScene, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.StoryID,
		&i.Title,
		&i.BeatIntent,
		&i.CharacterRefs,
		&i.LocationRef,
		&i.Pov,
		&i.Tone,
		&i.TargetWords,
		&i.SceneStructure,
		&i.ParentSceneID,
		&i.TimelinePosition,
		&i.FlowType,
		&i.MaxTurns,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSceneSummary = `-- name: GetSceneSummary :one
SELECT id, story_id, scene_id, level, content, word_count, created_at FROM story_summaries
WHERE story_id = $1 AND scene_id = $2 AND level = 'scene'
`

type GetSceneSummaryParams struct {
	StoryID pgtype.UUID `json:"story_id"`
	SceneID pgtype.UUID `json:"scene_id"`
}

func (q *Queries) GetSceneSummary(ctx context.Context, arg GetSceneSummaryParams) (StorySummary, error) {
	row := q.db.QueryRow(ctx, getSceneSummary, arg.StoryID, arg.SceneID)
	var i StorySummary
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.SceneID,
		&i.Level,
		&i.Content,
		&i.WordCount,
		&i.CreatedAt,
	)
	return i, err
}

const getStatesAtBranch = `-- name: GetStatesAtBranch :many
SELECT DISTINCT ON (cs.character_id) cs.story_id, cs.character_id, cs.as_of_scene, cs.state, cs.updated_at
FROM character_state cs
WHERE cs.story_id = $1 AND cs.as_of_scene = $2
ORDER BY cs.character_id, cs.as_of_scene DESC
`

type GetStatesAtBranchParams struct {
	StoryID   pgtype.UUID `json:"story_id"`
	AsOfScene pgtype.UUID `json:"as_of_scene"`
}

func (q *Queries) GetStatesAtBranch(ctx context.Context, arg GetStatesAtBranchParams) ([]CharacterState, error) {
	rows, err := q.db.Query(ctx, getStatesAtBranch, arg.StoryID, arg.AsOfScene)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterState{}
	for rows.Next() {
		var i CharacterState
		if err := rows.Scan(
			&i.StoryID,
			&i.CharacterID,
			&i.AsOfScene,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatesForScene = `-- name: GetStatesForScene :many
SELECT story_id, character_id, as_of_scene, state, updated_at FROM character_state
WHERE story_id = $1 AND as_of_scene = $2
`

type GetStatesForSceneParams struct {
	StoryID   pgtype.UUID `json:"story_id"`
	AsOfScene pgtype.UUID `json:"as_of_scene"`
}

func (q *Queries) GetStatesForScene(ctx context.Context, arg GetStatesForSceneParams) ([]CharacterState, error) {
	rows, err := q.db.Query(ctx, getStatesForScene, arg.StoryID, arg.AsOfScene)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterState{}
	for rows.Next() {
		var i CharacterState
		if err := rows.Scan(
			&i.StoryID,
			&i.CharacterID,
			&i.AsOfScene,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStory = `-- name: GetStory :one
SELECT id, title, canon_pins, created_at, genre, theme, main_prompt, general_prompt FROM stories WHERE id = $1
`

func (q *Queries) GetStory(ctx context.Context, id pgtype.UUID) (Story, error) {
	row := q.db.QueryRow(ctx, getStory, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CanonPins,
		&i.CreatedAt,
		&i.Genre,
		&i.Theme,
		&i.MainPrompt,
		&i.GeneralPrompt,
	)
	return i, err
}

const getSummaryByLevel = `-- name: GetSummaryByLevel :one
SELECT id, story_id, scene_id, level, content, word_count, created_at FROM story_summaries
WHERE story_id = $1 AND level = $2
ORDER BY created_at DESC LIMIT 1
`

type GetSummaryByLevelParams struct {
	StoryID pgtype.UUID `json:"story_id"`
	Level   string      `json:"level"`
}

func (q *Queries) GetSummaryByLevel(ctx context.Context, arg GetSummaryByLevelParams) (StorySummary, error) {
	row := q.db.QueryRow(ctx, getSummaryByLevel, arg.StoryID, arg.Level)
	var i StorySummary
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.SceneID,
		&i.Level,
		&i.Content,
		&i.WordCount,
		&i.CreatedAt,
	)
	return i, err
}

const getTraitAssignments = `-- name: GetTraitAssignments :many
SELECT ca.character_id, ca.trait_id, ca.intensity, ca.note, ct.name, ct.category, ct.description
FROM character_trait_assignments ca
JOIN character_traits ct ON ct.id = ca.trait_id
WHERE ca.character_id = $1
ORDER BY ct.name
`

type GetTraitAssignmentsRow struct {
	CharacterID pgtype.UUID `json:"character_id"`
	TraitID     pgtype.UUID `json:"trait_id"`
	Intensity   int32       `json:"intensity"`
	Note        string      `json:"note"`
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Description string      `json:"description"`
}

func (q *Queries) GetTraitAssignments(ctx context.Context, characterID pgtype.UUID) ([]GetTraitAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getTraitAssignments, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTraitAssignmentsRow{}
	for rows.Next() {
		var i GetTraitAssignmentsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.TraitID,
			&i.Intensity,
			&i.Note,
			&i.Name,
			&i.Category,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGenerationStale = `-- name: IsGenerationStale :one
SELECT COUNT(*) > 0 FROM generations
WHERE scene_id = $1 AND context_hash != $2
`

type IsGenerationStaleParams struct {
	SceneID     pgtype.UUID `json:"scene_id"`
	ContextHash string      `json:"context_hash"`
}

func (q *Queries) IsGenerationStale(ctx context.Context, arg IsGenerationStaleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGenerationStale, arg.SceneID, arg.ContextHash)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listActors = `-- name: ListActors :many
SELECT id, name, gender, ethnicity, race, skin_tone, eye_color, hair_color, hair_style, build, height_cm, weight_kg, age, nationality, traits, created_at FROM actors ORDER BY name
`

func (q *Queries) ListActors(ctx context.Context) ([]Actor, error) {
	rows, err := q.db.Query(ctx, listActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Actor{}
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.Ethnicity,
			&i.Race,
			&i.SkinTone,
			&i.EyeColor,
			&i.HairColor,
			&i.HairStyle,
			&i.Build,
			&i.HeightCm,
			&i.WeightKg,
			&i.Age,
			&i.Nationality,
			&i.Traits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCastingForActor = `-- name: ListCastingForActor :many
SELECT c.id, c.story_id, c.actor_id, c.character_id, c.role_type, c.created_at, ch.name AS character_name, s.title AS story_title
FROM casting c
JOIN characters ch ON ch.id = c.character_id
JOIN stories s ON s.id = c.story_id
WHERE c.actor_id = $1
ORDER BY c.created_at
`

type ListCastingForActorRow struct {
	ID            pgtype.UUID        `json:"id"`
	StoryID       pgtype.UUID        `json:"story_id"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	CharacterID   pgtype.UUID        `json:"character_id"`
	RoleType      string             `json:"role_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CharacterName string             `json:"character_name"`
	StoryTitle    string             `json:"story_title"`
}

func (q *Queries) ListCastingForActor(ctx context.Context, actorID pgtype.UUID) ([]ListCastingForActorRow, error) {
	rows, err := q.db.Query(ctx, listCastingForActor, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCastingForActorRow{}
	for rows.Next() {
		var i ListCastingForActorRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ActorID,
			&i.CharacterID,
			&i.RoleType,
			&i.CreatedAt,
			&i.CharacterName,
			&i.StoryTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCastingForCharacter = `-- name: ListCastingForCharacter :many
SELECT c.id, c.story_id, c.actor_id, c.character_id, c.role_type, c.created_at, a.name AS actor_name, s.title AS story_title
FROM casting c
JOIN actors a ON a.id = c.actor_id
JOIN stories s ON s.id = c.story_id
WHERE c.character_id = $1
ORDER BY c.created_at
`

type ListCastingForCharacterRow struct {
	ID          pgtype.UUID        `json:"id"`
	StoryID     pgtype.UUID        `json:"story_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	RoleType    string             `json:"role_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorName   string             `json:"actor_name"`
	StoryTitle  string             `json:"story_title"`
}

func (q *Queries) ListCastingForCharacter(ctx context.Context, characterID pgtype.UUID) ([]ListCastingForCharacterRow, error) {
	rows, err := q.db.Query(ctx, listCastingForCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCastingForCharacterRow{}
	for rows.Next() {
		var i ListCastingForCharacterRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ActorID,
			&i.CharacterID,
			&i.RoleType,
			&i.CreatedAt,
			&i.ActorName,
			&i.StoryTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCastingForStory = `-- name: ListCastingForStory :many
SELECT c.id, c.story_id, c.actor_id, c.character_id, c.role_type, c.created_at, a.name AS actor_name, ch.name AS character_name
FROM casting c
JOIN actors a ON a.id = c.actor_id
JOIN characters ch ON ch.id = c.character_id
WHERE c.story_id = $1
ORDER BY c.created_at
`

type ListCastingForStoryRow struct {
	ID            pgtype.UUID        `json:"id"`
	StoryID       pgtype.UUID        `json:"story_id"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	CharacterID   pgtype.UUID        `json:"character_id"`
	RoleType      string             `json:"role_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorName     string             `json:"actor_name"`
	CharacterName string             `json:"character_name"`
}

func (q *Queries) ListCastingForStory(ctx context.Context, storyID pgtype.UUID) ([]ListCastingForStoryRow, error) {
	rows, err := q.db.Query(ctx, listCastingForStory, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCastingForStoryRow{}
	for rows.Next() {
		var i ListCastingForStoryRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ActorID,
			&i.CharacterID,
			&i.RoleType,
			&i.CreatedAt,
			&i.ActorName,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChapters = `-- name: ListChapters :many
SELECT id, story_id, title, goal, order_index, summary, status, created_at, updated_at FROM chapters WHERE story_id = $1 ORDER BY order_index
`

func (q *Queries) ListChapters(ctx context.Context, storyID pgtype.UUID) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChapters, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.Title,
			&i.Goal,
			&i.OrderIndex,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterTraits = `-- name: ListCharacterTraits :many
SELECT id, name, category, description, created_at FROM character_traits ORDER BY name
`

func (q *Queries) ListCharacterTraits(ctx context.Context) ([]CharacterTrait, error) {
	rows, err := q.db.Query(ctx, listCharacterTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterTrait{}
	for rows.Next() {
		var i CharacterTrait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, version, name, persona, backstory, moral_alignment, personality, flaws, goals, traits, voice_samples, relationships, parent_id, created_at FROM latest_characters ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]LatestCharacter, error) {
	rows, err := q.db.Query(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestCharacter{}
	for rows.Next() {
		var i LatestCharacter
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Name,
			&i.Persona,
			&i.Backstory,
			&i.MoralAlignment,
			&i.Personality,
			&i.Flaws,
			&i.Goals,
			&i.Traits,
			&i.VoiceSamples,
			&i.Relationships,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationsForScene = `-- name: ListGenerationsForScene :many
SELECT id, scene_id, context_hash, prompt_snapshot, output, model, accepted, created_at, validation_result FROM generations WHERE scene_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGenerationsForScene(ctx context.Context, sceneID pgtype.UUID) ([]Generation, error) {
	rows, err := q.db.Query(ctx, listGenerationsForScene, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Generation{}
	for rows.Next() {
		var i Generation
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.ContextHash,
			&i.PromptSnapshot,
			&i.Output,
			&i.Model,
			&i.Accepted,
			&i.CreatedAt,
			&i.ValidationResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, version, name, description, props, created_at FROM latest_locations ORDER BY name
`

func (q *Queries) ListLocations(ctx context.Context) ([]LatestLocation, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestLocation{}
	for rows.Next() {
		var i LatestLocation
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Props,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLore = `-- name: ListLore :many
SELECT id, tags, content, embedding, created_at FROM lore ORDER BY created_at DESC
`

func (q *Queries) ListLore(ctx context.Context) ([]Lore, error) {
	rows, err := q.db.Query(ctx, listLore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lore{}
	for rows.Next() {
		var i Lore
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneEdges = `-- name: ListSceneEdges :many
SELECT story_id, from_scene, to_scene, edge_type, condition FROM scene_edges WHERE story_id = $1
`

func (q *Queries) ListSceneEdges(ctx context.Context, storyID pgtype.UUID) ([]SceneEdge, error) {
	rows, err := q.db.Query(ctx, listSceneEdges, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneEdge{}
	for rows.Next() {
		var i SceneEdge
		if err := rows.Scan(
			&i.StoryID,
			&i.FromScene,
			&i.ToScene,
			&i.EdgeType,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSceneTurns = `-- name: ListSceneTurns :many
SELECT id, scene_id, turn_number, actor_ids, prompt, output, model, status, created_at FROM scene_turns WHERE scene_id = $1 ORDER BY turn_number
`

func (q *Queries) ListSceneTurns(ctx context.Context, sceneID pgtype.UUID) ([]SceneTurn, error) {
	rows, err := q.db.Query(ctx, listSceneTurns, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneTurn{}
	for rows.Next() {
		var i SceneTurn
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.TurnNumber,
			&i.ActorIds,
			&i.Prompt,
			&i.Output,
			&i.Model,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenes = `-- name: ListScenes :many
SELECT id, chapter_id, story_id, title, beat_intent, character_refs, location_ref, pov, tone, target_words, scene_structure, parent_scene_id, timeline_position, flow_type, max_turns, status, created_at, updated_at FROM scenes WHERE story_id = $1 ORDER BY created_at
`

func (q *Queries) ListScenes(ctx context.Context, storyID pgtype.UUID) ([]Scene, error) {
	rows, err := q.db.Query(ctx, listScenes, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.StoryID,
			&i.Title,
			&i.BeatIntent,
			&i.CharacterRefs,
			&i.LocationRef,
			&i.Pov,
			&i.Tone,
			&i.TargetWords,
			&i.SceneStructure,
			&i.ParentSceneID,
			&i.TimelinePosition,
			&i.FlowType,
			&i.MaxTurns,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenesByChapter = `-- name: ListScenesByChapter :many
SELECT id, chapter_id, story_id, title, beat_intent, character_refs, location_ref, pov, tone, target_words, scene_structure, parent_scene_id, timeline_position, flow_type, max_turns, status, created_at, updated_at FROM scenes WHERE chapter_id = $1 ORDER BY created_at
`

func (q *Queries) ListScenesByChapter(ctx context.Context, chapterID pgtype.UUID) ([]Scene, error) {
	rows, err := q.db.Query(ctx, listScenesByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.StoryID,
			&i.Title,
			&i.BeatIntent,
			&i.CharacterRefs,
			&i.LocationRef,
			&i.Pov,
			&i.Tone,
			&i.TargetWords,
			&i.SceneStructure,
			&i.ParentSceneID,
			&i.TimelinePosition,
			&i.FlowType,
			&i.MaxTurns,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStories = `-- name: ListStories :many
SELECT id, title, canon_pins, created_at, genre, theme, main_prompt, general_prompt FROM stories ORDER BY created_at DESC
`

func (q *Queries) ListStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.Query(ctx, listStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CanonPins,
			&i.CreatedAt,
			&i.Genre,
			&i.Theme,
			&i.MainPrompt,
			&i.GeneralPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesByLevel = `-- name: ListSummariesByLevel :many
SELECT id, story_id, scene_id, level, content, word_count, created_at FROM story_summaries
WHERE story_id = $1 AND level = $2
ORDER BY created_at DESC
`

type ListSummariesByLevelParams struct {
	StoryID pgtype.UUID `json:"story_id"`
	Level   string      `json:"level"`
}

func (q *Queries) ListSummariesByLevel(ctx context.Context, arg ListSummariesByLevelParams) ([]StorySummary, error) {
	rows, err := q.db.Query(ctx, listSummariesByLevel, arg.StoryID, arg.Level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorySummary{}
	for rows.Next() {
		var i StorySummary
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.SceneID,
			&i.Level,
			&i.Content,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectOtherGenerations = `-- name: RejectOtherGenerations :exec
UPDATE generations SET accepted = false
WHERE scene_id = $1 AND id != $2
`

type RejectOtherGenerationsParams struct {
	SceneID pgtype.UUID `json:"scene_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) RejectOtherGenerations(ctx context.Context, arg RejectOtherGenerationsParams) error {
	_, err := q.db.Exec(ctx, rejectOtherGenerations, arg.SceneID, arg.ID)
	return err
}

const searchCharacters = `-- name: SearchCharacters :many
SELECT id, version, name, persona, backstory, moral_alignment, personality, flaws, goals, traits, voice_samples, relationships, parent_id, created_at FROM latest_characters
WHERE
	to_tsvector('english', coalesce(name, '') || ' ' || coalesce(persona, '') || ' ' || coalesce(moral_alignment, '')) @@ plainto_tsquery('english', $1::text)
	OR $1 = ''
ORDER BY name
LIMIT $2
`

type SearchCharactersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchCharacters(ctx context.Context, arg SearchCharactersParams) ([]LatestCharacter, error) {
	rows, err := q.db.Query(ctx, searchCharacters, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestCharacter{}
	for rows.Next() {
		var i LatestCharacter
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Name,
			&i.Persona,
			&i.Backstory,
			&i.MoralAlignment,
			&i.Personality,
			&i.Flaws,
			&i.Goals,
			&i.Traits,
			&i.VoiceSamples,
			&i.Relationships,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLoreByTags = `-- name: SearchLoreByTags :many
SELECT id, tags, content, embedding, created_at FROM lore WHERE tags && $1::text[] ORDER BY created_at DESC
`

func (q *Queries) SearchLoreByTags(ctx context.Context, dollar_1 []string) ([]Lore, error) {
	rows, err := q.db.Query(ctx, searchLoreByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lore{}
	for rows.Next() {
		var i Lore
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLoreSimilar = `-- name: SearchLoreSimilar :many
SELECT id, tags, content, embedding, created_at FROM lore
ORDER BY embedding <=> $1::vector
LIMIT $2
`

type SearchLoreSimilarParams struct {
	Column1 pgvector.Vector `json:"column_1"`
	Limit   int32           `json:"limit"`
}

func (q *Queries) SearchLoreSimilar(ctx context.Context, arg SearchLoreSimilarParams) ([]Lore, error) {
	rows, err := q.db.Query(ctx, searchLoreSimilar, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lore{}
	for rows.Next() {
		var i Lore
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSceneStatus = `-- name: SetSceneStatus :exec
UPDATE scenes SET status = $2, updated_at = now() WHERE id = $1
`

type SetSceneStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetSceneStatus(ctx context.Context, arg SetSceneStatusParams) error {
	_, err := q.db.Exec(ctx, setSceneStatus, arg.ID, arg.Status)
	return err
}

const unassignTrait = `-- name: UnassignTrait :exec
DELETE FROM character_trait_assignments WHERE character_id = $1 AND trait_id = $2
`

type UnassignTraitParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	TraitID     pgtype.UUID `json:"trait_id"`
}

func (q *Queries) UnassignTrait(ctx context.Context, arg UnassignTraitParams) error {
	_, err := q.db.Exec(ctx, unassignTrait, arg.CharacterID, arg.TraitID)
	return err
}

const updateActor = `-- name: UpdateActor :one
UPDATE actors SET
  name = $2, gender = $3, ethnicity = $4, race = $5,
  skin_tone = $6, eye_color = $7, hair_color = $8, hair_style = $9,
  build = $10, height_cm = $11, weight_kg = $12, age = $13,
  nationality = $14, traits = CAST($15 AS jsonb)
WHERE id = $1
RETURNING id, name, gender, ethnicity, race, skin_tone, eye_color, hair_color, hair_style, build, height_cm, weight_kg, age, nationality, traits, created_at
`

type UpdateActorParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Gender      string      `json:"gender"`
	Ethnicity   string      `json:"ethnicity"`
	Race        string      `json:"race"`
	SkinTone    string      `json:"skin_tone"`
	EyeColor    string      `json:"eye_color"`
	HairColor   string      `json:"hair_color"`
	HairStyle   string      `json:"hair_style"`
	Build       string      `json:"build"`
	HeightCm    int32       `json:"height_cm"`
	WeightKg    int32       `json:"weight_kg"`
	Age         int32       `json:"age"`
	Nationality string      `json:"nationality"`
	Column15    []byte      `json:"column_15"`
}

func (q *Queries) UpdateActor(ctx context.Context, arg UpdateActorParams) (Actor, error) {
	row := q.db.QueryRow(ctx, updateActor,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.Ethnicity,
		arg.Race,
		arg.SkinTone,
		arg.EyeColor,
		arg.HairColor,
		arg.HairStyle,
		arg.Build,
		arg.HeightCm,
		arg.WeightKg,
		arg.Age,
		arg.Nationality,
		arg.Column15,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.Ethnicity,
		&i.Race,
		&i.SkinTone,
		&i.EyeColor,
		&i.HairColor,
		&i.HairStyle,
		&i.Build,
		&i.HeightCm,
		&i.WeightKg,
		&i.Age,
		&i.Nationality,
		&i.Traits,
		&i.CreatedAt,
	)
	return i, err
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE chapters SET
    title = $2, goal = $3, order_index = $4, summary = $5, status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, story_id, title, goal, order_index, summary, status, created_at, updated_at
`

type UpdateChapterParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Goal       string      `json:"goal"`
	OrderIndex int32       `json:"order_index"`
	Summary    string      `json:"summary"`
	Status     string      `json:"status"`
}

func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapter,
		arg.ID,
		arg.Title,
		arg.Goal,
		arg.OrderIndex,
		arg.Summary,
		arg.Status,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Title,
		&i.Goal,
		&i.OrderIndex,
		&i.Summary,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacter = `-- name: UpdateCharacter :one
INSERT INTO characters (id, version, name, persona, backstory, moral_alignment, personality, flaws, goals, traits, voice_samples, relationships, parent_id)
SELECT c.id, MAX(c.version) + 1, $2, $3, $4, $5, CAST($6 AS jsonb), CAST($7 AS jsonb), CAST($8 AS jsonb), CAST($9 AS jsonb), $10, CAST($11 AS jsonb), $12
FROM characters c WHERE c.id = $1
GROUP BY c.id
RETURNING id, version, name, traits, voice_samples, relationships, created_at, persona, backstory, moral_alignment, personality, flaws, goals, parent_id
`

type UpdateCharacterParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Persona        string      `json:"persona"`
	Backstory      string      `json:"backstory"`
	MoralAlignment string      `json:"moral_alignment"`
	Column6        []byte      `json:"column_6"`
	Column7        []byte      `json:"column_7"`
	Column8        []byte      `json:"column_8"`
	Column9        []byte      `json:"column_9"`
	VoiceSamples   []string    `json:"voice_samples"`
	Column11       []byte      `json:"column_11"`
	ParentID       pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.ID,
		arg.Name,
		arg.Persona,
		arg.Backstory,
		arg.MoralAlignment,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.VoiceSamples,
		arg.Column11,
		arg.ParentID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Traits,
		&i.VoiceSamples,
		&i.Relationships,
		&i.CreatedAt,
		&i.Persona,
		&i.Backstory,
		&i.MoralAlignment,
		&i.Personality,
		&i.Flaws,
		&i.Goals,
		&i.ParentID,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
INSERT INTO locations (id, version, name, description, props)
SELECT $1, MAX(version) + 1, name, $2, CAST($3 AS jsonb)
FROM locations WHERE id = $1
GROUP BY id, name
RETURNING id, version, name, description, props, created_at
`

type UpdateLocationParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	Column3     []byte      `json:"column_3"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation, arg.ID, arg.Description, arg.Column3)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Props,
		&i.CreatedAt,
	)
	return i, err
}

const updateScene = `-- name: UpdateScene :one
UPDATE scenes SET
    beat_intent = $2, character_refs = $3, location_ref = $4,
    pov = $5, tone = $6, target_words = $7,
    scene_structure = $8, title = $9, timeline_position = $10,
    flow_type = $11, max_turns = $12, updated_at = now()
WHERE id = $1
RETURNING id, chapter_id, story_id, title, beat_intent, character_refs, location_ref, pov, tone, target_words, scene_structure, parent_scene_id, timeline_position, flow_type, max_turns, status, created_at, updated_at
`

type UpdateSceneParams struct {
	ID               pgtype.UUID   `json:"id"`
	BeatIntent       string        `json:"beat_intent"`
	CharacterRefs    []pgtype.UUID `json:"character_refs"`
	LocationRef      pgtype.UUID   `json:"location_ref"`
	Pov              string        `json:"pov"`
	Tone             string        `json:"tone"`
	TargetWords      int32         `json:"target_words"`
	SceneStructure   []byte        `json:"scene_structure"`
	Title            string        `json:"title"`
	TimelinePosition string        `json:"timeline_position"`
	FlowType         string        `json:"flow_type"`
	MaxTurns         int32         `json:"max_turns"`
}

func (q *Queries) UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, updateScene,
		arg.ID,
		arg.BeatIntent,
		arg.CharacterRefs,
		arg.LocationRef,
		arg.Pov,
		arg.Tone,
		arg.TargetWords,
		arg.SceneStructure,
		arg.Title,
		arg.TimelinePosition,
		arg.FlowType,
		arg.MaxTurns,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.StoryID,
		&i.Title,
		&i.BeatIntent,
		&i.CharacterRefs,
		&i.LocationRef,
		&i.Pov,
		&i.Tone,
		&i.TargetWords,
		&i.SceneStructure,
		&i.ParentSceneID,
		&i.TimelinePosition,
		&i.FlowType,
		&i.MaxTurns,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSceneStructure = `-- name: UpdateSceneStructure :exec
UPDATE scenes SET scene_structure = $2, updated_at = now() WHERE id = $1
`

type UpdateSceneStructureParams struct {
	ID             pgtype.UUID `json:"id"`
	SceneStructure []byte      `json:"scene_structure"`
}

func (q *Queries) UpdateSceneStructure(ctx context.Context, arg UpdateSceneStructureParams) error {
	_, err := q.db.Exec(ctx, updateSceneStructure, arg.ID, arg.SceneStructure)
	return err
}

const updateStory = `-- name: UpdateStory :one
UPDATE stories SET
    title = $2, genre = $3, theme = $4,
    main_prompt = $5, general_prompt = $6
WHERE id = $1
RETURNING id, title, canon_pins, created_at, genre, theme, main_prompt, general_prompt
`

type UpdateStoryParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	Genre         string      `json:"genre"`
	Theme         string      `json:"theme"`
	MainPrompt    string      `json:"main_prompt"`
	GeneralPrompt string      `json:"general_prompt"`
}

func (q *Queries) UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, updateStory,
		arg.ID,
		arg.Title,
		arg.Genre,
		arg.Theme,
		arg.MainPrompt,
		arg.GeneralPrompt,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CanonPins,
		&i.CreatedAt,
		&i.Genre,
		&i.Theme,
		&i.MainPrompt,
		&i.GeneralPrompt,
	)
	return i, err
}

const updateStoryCanonPins = `-- name: UpdateStoryCanonPins :exec
UPDATE stories SET canon_pins = $2 WHERE id = $1
`

type UpdateStoryCanonPinsParams struct {
	ID        pgtype.UUID `json:"id"`
	CanonPins []byte      `json:"canon_pins"`
}

func (q *Queries) UpdateStoryCanonPins(ctx context.Context, arg UpdateStoryCanonPinsParams) error {
	_, err := q.db.Exec(ctx, updateStoryCanonPins, arg.ID, arg.CanonPins)
	return err
}

const upsertActSummary = `-- name: UpsertActSummary :exec
INSERT INTO story_summaries (story_id, scene_id, level, content, word_count)
VALUES ($1, NULL, 'act', $2, $3)
ON CONFLICT (story_id, level) WHERE level = 'act' AND scene_id IS NULL
DO UPDATE SET content = $2, word_count = $3
`

type UpsertActSummaryParams struct {
	StoryID   pgtype.UUID `json:"story_id"`
	Content   string      `json:"content"`
	WordCount int32       `json:"word_count"`
}

func (q *Queries) UpsertActSummary(ctx context.Context, arg UpsertActSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertActSummary, arg.StoryID, arg.Content, arg.WordCount)
	return err
}

const upsertCharacterState = `-- name: UpsertCharacterState :exec

INSERT INTO character_state (story_id, character_id, as_of_scene, state)
VALUES ($1, $2, $3, $4)
ON CONFLICT (story_id, character_id, as_of_scene)
DO UPDATE SET state = $4, updated_at = now()
`

type UpsertCharacterStateParams struct {
	StoryID     pgtype.UUID `json:"story_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	AsOfScene   pgtype.UUID `json:"as_of_scene"`
	State       []byte      `json:"state"`
}

// ── Character State ──────────────────────────────────────────────────
func (q *Queries) UpsertCharacterState(ctx context.Context, arg UpsertCharacterStateParams) error {
	_, err := q.db.Exec(ctx, upsertCharacterState,
		arg.StoryID,
		arg.CharacterID,
		arg.AsOfScene,
		arg.State,
	)
	return err
}

const upsertSceneSummary = `-- name: UpsertSceneSummary :exec

INSERT INTO story_summaries (story_id, scene_id, level, content, word_count)
VALUES ($1, $2, 'scene', $3, $4)
ON CONFLICT (story_id, scene_id) WHERE level = 'scene' AND scene_id IS NOT NULL
DO UPDATE SET content = $3, word_count = $4
`

type UpsertSceneSummaryParams struct {
	StoryID   pgtype.UUID `json:"story_id"`
	SceneID   pgtype.UUID `json:"scene_id"`
	Content   string      `json:"content"`
	WordCount int32       `json:"word_count"`
}

// ── Summaries ────────────────────────────────────────────────────────
func (q *Queries) UpsertSceneSummary(ctx context.Context, arg UpsertSceneSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertSceneSummary,
		arg.StoryID,
		arg.SceneID,
		arg.Content,
		arg.WordCount,
	)
	return err
}

const upsertStorySummary = `-- name: UpsertStorySummary :exec
INSERT INTO story_summaries (story_id, scene_id, level, content, word_count)
VALUES ($1, NULL, 'story', $2, $3)
ON CONFLICT (story_id, level) WHERE level = 'story' AND scene_id IS NULL
DO UPDATE SET content = $2, word_count = $3
`

type UpsertStorySummaryParams struct {
	StoryID   pgtype.UUID `json:"story_id"`
	Content   string      `json:"content"`
	WordCount int32       `json:"word_count"`
}

func (q *Queries) UpsertStorySummary(ctx context.Context, arg UpsertStorySummaryParams) error {
	_, err := q.db.Exec(ctx, upsertStorySummary, arg.StoryID, arg.Content, arg.WordCount)
	return err
}
