// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptGeneration(ctx context.Context, id pgtype.UUID) error
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	CreateEdge(ctx context.Context, arg CreateEdgeParams) error
	CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateLore(ctx context.Context, arg CreateLoreParams) (Lore, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateStory(ctx context.Context, title string) (Story, error)
	GetAcceptedGenerationForNode(ctx context.Context, nodeID pgtype.UUID) (Generation, error)
	GetCharacterAtVersion(ctx context.Context, arg GetCharacterAtVersionParams) (Character, error)
	GetCharacterLatest(ctx context.Context, id pgtype.UUID) (LatestCharacter, error)
	GetCharacterState(ctx context.Context, arg GetCharacterStateParams) (CharacterState, error)
	GetIncomingEdges(ctx context.Context, toNode pgtype.UUID) ([]Edge, error)
	GetLocationAtVersion(ctx context.Context, arg GetLocationAtVersionParams) (Location, error)
	GetLocationLatest(ctx context.Context, id pgtype.UUID) (LatestLocation, error)
	GetNode(ctx context.Context, id pgtype.UUID) (Node, error)
	GetOutgoingEdges(ctx context.Context, fromNode pgtype.UUID) ([]Edge, error)
	GetStatesAtBranch(ctx context.Context, arg GetStatesAtBranchParams) ([]CharacterState, error)
	GetStatesForNode(ctx context.Context, arg GetStatesForNodeParams) ([]CharacterState, error)
	GetStory(ctx context.Context, id pgtype.UUID) (Story, error)
	IsGenerationStale(ctx context.Context, arg IsGenerationStaleParams) (bool, error)
	ListCharacters(ctx context.Context) ([]LatestCharacter, error)
	ListEdges(ctx context.Context, storyID pgtype.UUID) ([]Edge, error)
	ListGenerationsForNode(ctx context.Context, nodeID pgtype.UUID) ([]Generation, error)
	ListLocations(ctx context.Context) ([]LatestLocation, error)
	ListLore(ctx context.Context) ([]Lore, error)
	ListNodes(ctx context.Context, storyID pgtype.UUID) ([]Node, error)
	ListStories(ctx context.Context) ([]Story, error)
	RejectOtherGenerations(ctx context.Context, arg RejectOtherGenerationsParams) error
	SearchLoreByTags(ctx context.Context, dollar_1 []string) ([]Lore, error)
	SearchLoreSimilar(ctx context.Context, arg SearchLoreSimilarParams) ([]Lore, error)
	SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error)
	UpdateStoryCanonPins(ctx context.Context, arg UpdateStoryCanonPinsParams) error
	UpsertCharacterState(ctx context.Context, arg UpsertCharacterStateParams) error
}

var _ Querier = (*Queries)(nil)
